name: mygreenpass
description: Simple app that stores European Digital Green Certificates digitally.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^1.0.3 # ^0.14.0+3 # https://pub.dev/packages/flutter_riverpod
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # QR code scanner (https://pub.dev/packages/qr_code_scanner)
  qr_code_scanner: ^0.5.2

  # Permission handler (https://pub.dev/packages/permission_handler)
  permission_handler: ^8.1.4+2

  # Dart COSE (https://pub.dev/packages/dart_cose)
  dart_cose: ^1.1.3

  # Dart COSE dependencies
  asn1lib: ^1.0.2 # import 'package:asn1lib/asn1lib.dart';
  cbor: ^4.1.0  # import 'package:cbor/cbor.dart';
  crypto: ^3.0.1 # import 'package:crypto/crypto.dart';
  crypto_keys: ^0.3.0 # import 'package:crypto_keys/crypto_keys.dart';
  dart_base45: ^1.0.1 # import 'package:dart_base45/dart_base45.dart';
  ninja: ^3.0.5 # import 'package:ninja/ninja.dart';
  x509b: ^0.2.5 # import 'package:x509b/x509.dart';
  intl: ^0.17.0 # import 'package:intl/intl.dart'; (for DateFormat)
  glassmorphism: ^2.0.1 # import 'package:glassmorphism/glassmorphism.dart';
  qr_flutter: ^4.0.0 # import 'package:qr_flutter/qr_flutter.dart';
  country_codes: ^2.0.1 # import 'package:country_codes/country_codes.dart';
  carousel_slider: ^4.0.0 # import 'package:carousel_slider/carousel_slider.dart';
  localstorage: ^4.0.0+1 # import 'package:localstorage/localstorage.dart';
  shared_preferences: ^2.0.7 # import 'package:shared_preferences/shared_preferences.dart';

  # Simple Shadow (https://pub.dev/packages/simple_shadow)
  simple_shadow: ^0.3.0 # import 'package:simple_shadow/simple_shadow.dart';
  url_launcher: ^6.0.10
  screen: ^0.0.5
  flutter_svg: ^1.0.0
  flutter_svg_opt: ^0.0.1
  flutter_linkify: ^5.0.2
  card_swiper: ^1.0.4
  flutter_reorderable_list: ^1.2.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # App icon (https://pub.dev/packages/flutter_launcher_icons)
  flutter_launcher_icons: "^0.9.2"

  # Flutter Native Splash (https://pub.dev/packages/flutter_native_splash)
  flutter_native_splash: ^1.2.3 # import 'package:flutter_native_splash/flutter_native_splash.dart';

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - data/

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
          weight: 400
        - asset: fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: fonts/RobotoMono-SemiBold.ttf
          weight: 600
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"

# https://stackoverflow.com/questions/43879103/adding-a-splash-screen-to-flutter-apps
# flutter pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/splash.png
  color: "ffffff"